name: Run Telegram Bot Evry 30 Minutes 

on:
  schedule:
    - cron: "*/27 * * * *"
  workflow_dispatch:         # allow manual run

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install python-telegram-bot==21.1

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMINS: ${{ secrets.ADMINS }}
        run: python bot.py
